apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-springboot-app-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1 # default is 25%
      maxUnavailable: 1 # default is 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-springboot-app
  replicas: 5
  template:
    metadata:
      labels:
        app: demo-springboot-app
    spec:
      containers:
        - name: demo-springboot-app
          image: lws/demo-springboot:v1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: JAVA_OPTS
              value: "-Duser.timezone=GMT+08"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-springboot-app-service
spec:
  type: NodePort
  selector:
    app: demo-springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31201
